// Data soal hasil konversi dari: soal simulasi day 10.docx
// Edit file ini untuk mengubah soal. Ganti text, image, options, dan answer sesuai kebutuhan.
// Gunakan image: '' bila soal tidak memiliki gambar.
export const examConfig = {
  title: 'Soal Simulasi Day 10',
  subject: 'Simulasi Pengetahuan Umum',
  durationMinutes: 120,
};

export const questions = [
  {
    id: 1,
    text: 'Stasiun radio ABC berasal dari negara …',
    image: '',
    options: {
      A: 'Inggris',
      B: 'Jepang',
      C: 'Australia',
      D: 'Amerika Serikat',
    },
    answer: 'C',
  },
  {
    id: 2,
    text: 'Kepanjangan BBC adalah …',
    image: '',
    options: {
      A: 'British Broadcasting Corporation',
      B: 'Broadcast Britain Center',
      C: 'British Broad Center',
      D: 'Broadcasting British Company',
    },
    answer: 'A',
  },
  {
    id: 3,
    text: 'NHK merupakan stasiun radio terkenal dari negara …',
    image: '',
    options: {
      A: 'Cina',
      B: 'Jepang',
      C: 'Korea',
      D: 'India',
    },
    answer: 'B',
  },
  {
    id: 4,
    text: 'VOA adalah singkatan dari …',
    image: '',
    options: {
      A: 'Voice of Asia',
      B: 'Voice of America',
      C: 'Voice of Australia',
      D: 'Voice of Africa',
    },
    answer: 'B',
  },
  {
    id: 5,
    text: 'Lagu kebangsaan Amerika Serikat adalah …',
    image: '',
    options: {
      A: 'Kimigayo',
      B: 'Advance Australia Fair',
      C: 'The Stars Spangled Banner',
      D: 'Fratelli d’Italia',
    },
    answer: 'C',
  },
  {
    id: 6,
    text: 'Lagu kebangsaan Jepang berjudul …',
    image: '',
    options: {
      A: 'Kimigayo',
      B: 'Maame',
      C: 'Wilhelmus',
      D: 'Negaraku',
    },
    answer: 'A',
  },
  {
    id: 7,
    text: 'Lagu kebangsaan Malaysia adalah …',
    image: '',
    options: {
      A: 'Negaraku',
      B: 'Oom Hemmect',
      C: 'Maame',
      D: 'Wilhelmus',
    },
    answer: 'A',
  },
  {
    id: 8,
    text: '“God Save The Queen” merupakan lagu kebangsaan negara …',
    image: '',
    options: {
      A: 'Jerman',
      B: 'Inggris',
      C: 'Belgia',
      D: 'India',
    },
    answer: 'B',
  },
  {
    id: 9,
    text: 'Lagu kebangsaan Belanda adalah …',
    image: '',
    options: {
      A: 'Wilhelmus',
      B: 'Kimigayo',
      C: 'Fratelli d’Italia',
      D: 'Duke Patria',
    },
    answer: 'A',
  },
  {
    id: 10,
    text: 'Maskapai penerbangan Garuda Indonesia termasuk penerbangan …',
    image: '',
    options: {
      A: 'Asing',
      B: 'Domestik',
      C: 'Regional',
      D: 'Charter',
    },
    answer: 'B',
  },
  {
    id: 11,
    text: 'MAS adalah maskapai penerbangan dari negara …',
    image: '',
    options: {
      A: 'Mesir',
      B: 'Malaysia',
      C: 'Jepang',
      D: 'India',
    },
    answer: 'B',
  },
  {
    id: 12,
    text: 'JAL merupakan singkatan dari …',
    image: '',
    options: {
      A: 'Japan Air Lines',
      B: 'Java Air Lines',
      C: 'Jakarta Airlines',
      D: 'Japan Aviation Limited',
    },
    answer: 'A',
  },
  {
    id: 13,
    text: 'Lufthansa adalah maskapai penerbangan dari negara …',
    image: '',
    options: {
      A: 'Italia',
      B: 'Inggris',
      C: 'Jerman',
      D: 'Belgia',
    },
    answer: 'C',
  },
  {
    id: 14,
    text: 'Cathay Pacific berasal dari negara …',
    image: '',
    options: {
      A: 'Hongkong',
      B: 'India',
      C: 'Korea Selatan',
      D: 'Pakistan',
    },
    answer: 'A',
  },
  {
    id: 15,
    text: 'Singapore Airlines disingkat …',
    image: '',
    options: {
      A: 'SAS',
      B: 'SIA',
      C: 'SAA',
      D: 'CSA',
    },
    answer: 'B',
  },
  {
    id: 16,
    text: 'Kantor berita resmi Indonesia adalah …',
    image: '',
    options: {
      A: 'Reuters',
      B: 'AFP',
      C: 'Antara',
      D: 'Bernama',
    },
    answer: 'C',
  },
  {
    id: 17,
    text: 'AFP berasal dari negara …',
    image: '',
    options: {
      A: 'Inggris',
      B: 'Amerika Serikat',
      C: 'Prancis',
      D: 'Jepang',
    },
    answer: 'C',
  },
  {
    id: 18,
    text: 'Reuters merupakan kantor berita dari negara …',
    image: '',
    options: {
      A: 'Inggris',
      B: 'Rusia',
      C: 'India',
      D: 'Iran',
    },
    answer: 'A',
  },
  {
    id: 19,
    text: 'Bernama adalah kantor berita negara …',
    image: '',
    options: {
      A: 'Thailand',
      B: 'Malaysia',
      C: 'Vietnam',
      D: 'India',
    },
    answer: 'B',
  },
  {
    id: 20,
    text: 'AP adalah singkatan dari …',
    image: '',
    options: {
      A: 'Asian Press',
      B: 'Associated Press',
      C: 'American Publisher',
      D: 'Agency Press',
    },
    answer: 'B',
  },
  {
    id: 21,
    text: 'Motto TNI AD adalah …',
    image: '',
    options: {
      A: 'Jalesveva Jayamahe',
      B: 'Swa Bhuwana Paksa',
      C: 'Kartika Eka Paksi',
      D: 'Rastra Sewakottama',
    },
    answer: 'C',
  },
  {
    id: 22,
    text: '“Di Laut Kita Jaya” merupakan arti dari motto …',
    image: '',
    options: {
      A: 'Kartika Eka Paksi',
      B: 'Rastra Sewakottama',
      C: 'Swa Bhuwana Paksa',
      D: 'Jalesveva Jayamahe',
    },
    answer: 'D',
  },
  {
    id: 23,
    text: 'Motto POLRI adalah …',
    image: '',
    options: {
      A: 'Rastra Sewakottama',
      B: 'Kartika Eka Paksi',
      C: 'Swa Bhuwana Paksa',
      D: 'Jalesveva Jayamahe',
    },
    answer: 'A',
  },
  {
    id: 24,
    text: 'Nama latin gajah adalah …',
    image: '',
    options: {
      A: 'Bos sundaicus',
      B: 'Elephas indicus',
      C: 'Crocodylus novaeguineae',
      D: 'Dugong dugong',
    },
    answer: 'B',
  },
  {
    id: 25,
    text: 'Babirusa memiliki nama latin …',
    image: '',
    options: {
      A: 'Babirussa babirussa',
      B: 'Panthera pardus',
      C: 'Pavo muticus',
      D: 'Trugulus',
    },
    answer: 'A',
  },
  {
    id: 26,
    text: 'Nama latin harimau Sumatera adalah …',
    image: '',
    options: {
      A: 'Panthera pardus',
      B: 'Panthera tigris sundaicus',
      C: 'Panthera tigris sumatranus',
      D: 'Elephas indicus',
    },
    answer: 'C',
  },
  {
    id: 27,
    text: 'Dugong dugong adalah nama latin dari hewan …',
    image: '',
    options: {
      A: 'Gajah',
      B: 'Lumba-lumba',
      C: 'Ikan duyung',
      D: 'Buaya',
    },
    answer: 'C',
  },
  {
    id: 28,
    text: 'Nama latin burung merak adalah …',
    image: '',
    options: {
      A: 'Pavo muticus',
      B: 'Casuarius casuarius',
      C: 'Muntiacus muntjak',
      D: 'Probosciger aterrimus',
    },
    answer: 'A',
  },
  {
    id: 29,
    text: 'Nama latin kasuari adalah …',
    image: '',
    options: {
      A: 'Crocodylus novaeguineae',
      B: 'Casuarius casuarius',
      C: 'Dugong dugong',
      D: 'Panthera pardus',
    },
    answer: 'B',
  },
  {
    id: 30,
    text: 'Panthera pardus merupakan nama latin dari …',
    image: '',
    options: {
      A: 'Harimau Jawa',
      B: 'Kijang',
      C: 'Macan kumbang',
      D: 'Kakaktua Raja',
    },
    answer: 'C',
  },
  {
    id: 31,
    text: 'Raja Dinuzulu meninggal pada tahun …',
    image: '',
    options: {
      A: '1910',
      B: '1911',
      C: '1912',
      D: '1913',
    },
    answer: 'D',
  },
  {
    id: 32,
    text: 'Buku yang ditulis BP setelah kembali ke Inggris tahun 1901 berjudul …',
    image: '',
    options: {
      A: 'Scouting for Boys',
      B: 'Aids to Scouting',
      C: 'The Jungle Book',
      D: 'Rovering to Success',
    },
    answer: 'B',
  },
  {
    id: 33,
    text: 'BP mendapat undangan dari perkumpulan Boys Brigade pada tahun …',
    image: '',
    options: {
      A: '1905',
      B: '1906',
      C: '1907',
      D: '1908',
    },
    answer: 'C',
  },
  {
    id: 34,
    text: 'Perkemahan di Pulau Brownsea diikuti oleh …',
    image: '',
    options: {
      A: '15 orang',
      B: '18 orang',
      C: '20 orang',
      D: '25 orang',
    },
    answer: 'C',
  },
  {
    id: 35,
    text: 'BP berhenti dari dinas kemiliteran pada tahun …',
    image: '',
    options: {
      A: '1908',
      B: '1909',
      C: '1910',
      D: '1911',
    },
    answer: 'C',
  },
  {
    id: 36,
    text: 'Pangkat terakhir Baden Powell adalah …',
    image: '',
    options: {
      A: 'Mayor Jenderal',
      B: 'Letnan Jenderal',
      C: 'Kolonel',
      D: 'Marsekal',
    },
    answer: 'B',
  },
  {
    id: 37,
    text: 'BP memulai perjalanan berkeliling dunia pada tahun …',
    image: '',
    options: {
      A: '1910',
      B: '1911',
      C: '1912',
      D: '1913',
    },
    answer: 'C',
  },
  {
    id: 38,
    text: 'Baden Powell diangkat sebagai Chief Scout of the World pada tanggal …',
    image: '',
    options: {
      A: '6 Agustus 1920',
      B: '16 Agustus 1920',
      C: '8 Januari 1941',
      D: '3 Desember 1934',
    },
    answer: 'A',
  },
  {
    id: 39,
    text: 'BP mengunjungi Batavia (Jakarta) pada tanggal …',
    image: '',
    options: {
      A: '1 Januari 1934',
      B: '3 Desember 1934',
      C: '6 Agustus 1934',
      D: '8 Januari 1935',
    },
    answer: 'B',
  },
  {
    id: 40,
    text: 'Baden Powell wafat pada tanggal …',
    image: '',
    options: {
      A: '8 Januari 1941',
      B: '6 Agustus 1920',
      C: '3 Desember 1934',
      D: '15 Januari 1908',
    },
    answer: 'A',
  },
  {
    id: 41,
    text: 'Buku Scouting for Boys pertama kali diedarkan pada tanggal …',
    image: '',
    options: {
      A: '1 Januari 1908',
      B: '15 Januari 1908',
      C: '10 Februari 1908',
      D: '20 Januari 1908',
    },
    answer: 'B',
  },
  {
    id: 42,
    text: 'Penerbit buku Scouting for Boys adalah …',
    image: '',
    options: {
      A: 'Oxford Press',
      B: 'Gramedia',
      C: 'Horace Cox',
      D: 'Cambridge Press',
    },
    answer: 'C',
  },
  {
    id: 43,
    text: 'Kepanduan siaga didirikan pada tahun …',
    image: '',
    options: {
      A: '1914',
      B: '1915',
      C: '1916',
      D: '1917',
    },
    answer: 'C',
  },
  {
    id: 44,
    text: 'Buku yang mengilhami kegiatan siaga adalah …',
    image: '',
    options: {
      A: 'Scouting for Boys',
      B: 'The Jungle Book',
      C: 'Aids to Scouting',
      D: 'Rovering to Success',
    },
    answer: 'B',
  },
  {
    id: 45,
    text: 'Penulis buku The Jungle Book adalah …',
    image: '',
    options: {
      A: 'Baden Powell',
      B: 'William McLaren',
      C: 'Rudyard Kipling',
      D: 'John Thurman',
    },
    answer: 'C',
  },
  {
    id: 46,
    text: 'Nama anak serigala dalam cerita The Jungle Book adalah …',
    image: '',
    options: {
      A: 'Simba',
      B: 'Tarzan',
      C: 'Mowgli',
      D: 'Bagheera',
    },
    answer: 'C',
  },
  {
    id: 47,
    text: 'Bagheera dan Baloo dalam cerita The Jungle Book adalah …',
    image: '',
    options: {
      A: 'Singa dan harimau',
      B: 'Macan kumbang dan beruang',
      C: 'Serigala dan rubah',
      D: 'Beruang dan gajah',
    },
    answer: 'B',
  },
  {
    id: 48,
    text: 'Sahabat BP yang memberikan sebidang tanah adalah …',
    image: '',
    options: {
      A: 'Rudyard Kipling',
      B: 'John Thurman',
      C: 'William F DeBois McLaren',
      D: 'Lord Baden',
    },
    answer: 'C',
  },
  {
    id: 49,
    text: 'Patung yang ada di Gilwell Park adalah patung …',
    image: '',
    options: {
      A: 'Harimau',
      B: 'Elang',
      C: 'Singa',
      D: 'Kuda',
    },
    answer: 'C',
  },
  {
    id: 50,
    text: 'Gerakan Pramuka menjadi satu-satunya organisasi kepanduan sejak Kepres nomor …',
    image: '',
    options: {
      A: '238/1961',
      B: '448/1961',
      C: '055/1982',
      D: '174/2012',
    },
    answer: 'A',
  },
  {
    id: 51,
    text: 'Skep Panji Gerakan Pramuka adalah nomor …',
    image: '',
    options: {
      A: '036 tahun 1979',
      B: '448 tahun 1961',
      C: '174 tahun 2012',
      D: '064 tahun 2001',
    },
    answer: 'B',
  },
  {
    id: 52,
    text: 'Surat keputusan Kwartir Nasional tentang lambang Gerakan Pramuka adalah …',
    image: '',
    options: {
      A: '06/KN/72',
      B: '045/KN/80',
      C: '055/1982',
      D: '132/KN/79',
    },
    answer: 'A',
  },
  {
    id: 53,
    text: 'Keputusan Kwarnas tentang tanda pengenal bernomor …',
    image: '',
    options: {
      A: '202/KN/88',
      B: '055 tahun 1982',
      C: '064 tahun 2001',
      D: '174/KN/2012',
    },
    answer: 'B',
  },
  {
    id: 54,
    text: 'Skep tentang tanda pengenal umum adalah …',
    image: '',
    options: {
      A: '059 Tahun 1982',
      B: '088 Tahun 1982',
      C: '045 Tahun 1980',
      D: '036 Tahun 1979',
    },
    answer: 'A',
  },
  {
    id: 55,
    text: 'SK Kwarnas tentang tanda kecakapan adalah …',
    image: '',
    options: {
      A: '055/1982 dan 036/1979',
      B: '088/KN/74 dan 058 tahun 1982',
      C: '202/KN/88 dan 045/1980',
      D: '174/2012 dan 132/1979',
    },
    answer: 'B',
  },
  {
    id: 56,
    text: 'SK Kwarnas nomor 064 tahun 2001 berisi tentang …',
    image: '',
    options: {
      A: 'Seragam pramuka',
      B: 'Lambang pramuka',
      C: 'Penarikan diri dari WAGGGS',
      D: 'Tanda jabatan',
    },
    answer: 'C',
  },
  {
    id: 57,
    text: 'Skep tentang TKK adalah nomor …',
    image: '',
    options: {
      A: '132/KN/79 dan 134/KN/76',
      B: '055/1982 dan 058/1982',
      C: '036/1979 dan 045/1980',
      D: '174/2012 dan 202/1988',
    },
    answer: 'A',
  },
  {
    id: 58,
    text: 'Skep tentang baju pramuka dahulu adalah …',
    image: '',
    options: {
      A: '045/KN/80',
      B: '088/KN/81',
      C: '202/KN/88',
      D: '174/KN/2012',
    },
    answer: 'B',
  },
  {
    id: 59,
    text: 'Skep baju pramuka yang sekarang adalah …',
    image: '',
    options: {
      A: '174/KN/2012',
      B: '036/KN/79',
      C: '055/1982',
      D: '064/2001',
    },
    answer: 'A',
  },
  {
    id: 60,
    text: 'Skep SKU terbaru adalah …',
    image: '',
    options: {
      A: '045/KN/80',
      B: '198/KN/2011',
      C: '132/KN/79',
      D: '202/KN/88',
    },
    answer: 'B',
  },
  {
    id: 61,
    text: 'Obat merah seperti mercurochrome atau betadine digunakan untuk …',
    image: '',
    options: {
      A: 'Obat sakit perut',
      B: 'Obat malaria',
      C: 'Obat luka baru yang ringan',
      D: 'Obat mata',
    },
    answer: 'C',
  },
  {
    id: 62,
    text: 'Yodium tinctur digunakan untuk …',
    image: '',
    options: {
      A: 'Luka berat atau lama',
      B: 'Sakit kepala',
      C: 'Luka bakar',
      D: 'Penyakit malaria',
    },
    answer: 'A',
  },
  {
    id: 63,
    text: 'Fungsi perbalse atau salep adalah untuk …',
    image: '',
    options: {
      A: 'Obat mata',
      B: 'Obat luka lama',
      C: 'Obat pusing',
      D: 'Obat batuk',
    },
    answer: 'B',
  },
  {
    id: 64,
    text: 'Amonia liquida digunakan untuk …',
    image: '',
    options: {
      A: 'Mengobati luka bakar',
      B: 'Membersihkan mata',
      C: 'Perangsang bagi orang pingsan',
      D: 'Mengobati demam',
    },
    answer: 'C',
  },
  {
    id: 65,
    text: 'Larutan burowi berfungsi sebagai …',
    image: '',
    options: {
      A: 'Obat sakit perut',
      B: 'Pembersih luka',
      C: 'Obat malaria',
      D: 'Penghangat tubuh',
    },
    answer: 'B',
  },
  {
    id: 66,
    text: 'Boorwater dapat digunakan untuk …',
    image: '',
    options: {
      A: 'Obat malaria',
      B: 'Pengering luka',
      C: 'Pembersih luka dan mata',
      D: 'Obat pingsan',
    },
    answer: 'C',
  },
  {
    id: 67,
    text: 'Zulfazincie digunakan sebagai …',
    image: '',
    options: {
      A: 'Obat luka',
      B: 'Obat mata',
      C: 'Obat batuk',
      D: 'Obat pusing',
    },
    answer: 'B',
  },
  {
    id: 68,
    text: 'Tablet norit digunakan untuk …',
    image: '',
    options: {
      A: 'Penyakit malaria',
      B: 'Sakit kepala',
      C: 'Keracunan dan sakit perut',
      D: 'Obat luka',
    },
    answer: 'C',
  },
  {
    id: 69,
    text: 'Tablet kina digunakan untuk penyakit …',
    image: '',
    options: {
      A: 'Campak',
      B: 'Malaria',
      C: 'TBC',
      D: 'Tetanus',
    },
    answer: 'B',
  },
  {
    id: 70,
    text: 'Paracetamol digunakan untuk mengatasi …',
    image: '',
    options: {
      A: 'Demam',
      B: 'Luka bakar',
      C: 'Keracunan',
      D: 'Pingsan',
    },
    answer: 'A',
  },
  {
    id: 71,
    text: 'Arang dapur dapat digunakan sebagai pengganti …',
    image: '',
    options: {
      A: 'Yodium',
      B: 'Paracetamol',
      C: 'Tablet norit',
      D: 'Boorwater',
    },
    answer: 'C',
  },
  {
    id: 72,
    text: 'Daun babadotan yang ditumbuk dapat digunakan sebagai pengganti …',
    image: '',
    options: {
      A: 'Obat merah',
      B: 'Tablet kina',
      C: 'Zulfazincie',
      D: 'Amoniak',
    },
    answer: 'A',
  },
  {
    id: 73,
    text: 'Lena (collapse/kolaps) disebabkan oleh …',
    image: '',
    options: {
      A: 'Kekurangan oksigen',
      B: 'Keracunan makanan',
      C: 'Infeksi mata',
      D: 'Penyakit malaria',
    },
    answer: 'A',
  },
  {
    id: 74,
    text: 'Gugat (shock) terjadi akibat …',
    image: '',
    options: {
      A: 'Terlalu banyak makan',
      B: 'Peristiwa yang mengejutkan',
      C: 'Kekurangan vitamin',
      D: 'Penyakit kulit',
    },
    answer: 'B',
  },
  {
    id: 75,
    text: 'Pernapasan buatan adalah usaha agar …',
    image: '',
    options: {
      A: 'Jantung bekerja kembali',
      B: 'Mata dapat melihat kembali',
      C: 'Paru-paru dapat bekerja kembali',
      D: 'Tubuh menjadi hangat',
    },
    answer: 'C',
  },
  {
    id: 76,
    text: 'Metode pernapasan buatan yang paling cepat dan efektif adalah …',
    image: '',
    options: {
      A: 'Howard',
      B: 'Schapter',
      C: 'Mulut ke mulut',
      D: 'Laborde',
    },
    answer: 'C',
  },
  {
    id: 77,
    text: 'Metode Hoger Nielsen disarankan untuk korban …',
    image: '',
    options: {
      A: 'Tenggelam',
      B: 'Keracunan',
      C: 'Luka bakar',
      D: 'Pingsan',
    },
    answer: 'A',
  },
  {
    id: 78,
    text: 'Pendarahan luar adalah …',
    image: '',
    options: {
      A: 'Darah keluar di dalam tubuh',
      B: 'Darah keluar dari tubuh',
      C: 'Darah berhenti mengalir',
      D: 'Darah membeku',
    },
    answer: 'B',
  },
  {
    id: 79,
    text: 'Darah dari pembuluh nadi berwarna …',
    image: '',
    options: {
      A: 'Merah tua',
      B: 'Hitam',
      C: 'Merah muda',
      D: 'Kuning',
    },
    answer: 'C',
  },
  {
    id: 80,
    text: 'Immunisasi artinya …',
    image: '',
    options: {
      A: 'Membersihkan darah',
      B: 'Menyuntikkan antigen untuk kekebalan',
      C: 'Mengobati luka',
      D: 'Mengobati demam',
    },
    answer: 'B',
  },
  {
    id: 81,
    text: 'Kompas adalah alat untuk …',
    image: '',
    options: {
      A: 'Menggambar peta',
      B: 'Menentukan arah mata angin',
      C: 'Mengukur suhu',
      D: 'Menghitung jarak',
    },
    answer: 'B',
  },
  {
    id: 82,
    text: 'Penemu kompas pertama kali adalah bangsa …',
    image: '',
    options: {
      A: 'Arab',
      B: 'Jepang',
      C: 'Cina',
      D: 'India',
    },
    answer: 'C',
  },
  {
    id: 83,
    text: 'Bagian kompas yang menunjukkan arah adalah …',
    image: '',
    options: {
      A: 'Dial',
      B: 'Visir',
      C: 'Jarum magnet',
      D: 'Kaca pembesar',
    },
    answer: 'C',
  },
  {
    id: 84,
    text: 'Sudut yang dihitung searah jarum jam dari arah utara disebut …',
    image: '',
    options: {
      A: 'Navigasi',
      B: 'Azimuth',
      C: 'Orientasi',
      D: 'Koordinat',
    },
    answer: 'B',
  },
  {
    id: 85,
    text: 'Timur berada pada derajat …',
    image: '',
    options: {
      A: '45°',
      B: '90°',
      C: '180°',
      D: '360°',
    },
    answer: 'B',
  },
  {
    id: 86,
    text: 'Arah antara selatan dan barat disebut …',
    image: '',
    options: {
      A: 'Barat laut',
      B: 'Tenggara',
      C: 'Barat daya',
      D: 'Timur laut',
    },
    answer: 'C',
  },
  {
    id: 87,
    text: 'Kompas yang sering digunakan dalam kegiatan pramuka dan orienteering adalah …',
    image: '',
    options: {
      A: 'Kompas Geologi',
      B: 'Kompas Digital',
      C: 'Kompas Bidik',
      D: 'Kompas Gyro',
    },
    answer: 'C',
  },
  {
    id: 88,
    text: 'Simbol pada peta untuk sungai atau kali adalah …',
    image: '',
    options: {
      A: 'Garis berkelok',
      B: 'Lingkaran',
      C: 'Kotak',
      D: 'Segitiga',
    },
    answer: 'A',
  },
  {
    id: 89,
    text: 'Tanda medan berbentuk pohon kelapa menunjukkan …',
    image: '',
    options: {
      A: 'Hutan jati',
      B: 'Kebun kelapa',
      C: 'Sawah',
      D: 'Semak',
    },
    answer: 'B',
  },
  {
    id: 90,
    text: 'Simbol huruf “L” pada tanda medan berarti …',
    image: '',
    options: {
      A: 'Ladang',
      B: 'Laut',
      C: 'Lapangan',
      D: 'Lembah',
    },
    answer: 'A',
  },
  {
    id: 91,
    text: 'Tanda medan berbentuk kotak dengan tanda bulan sabit menunjukkan …',
    image: '',
    options: {
      A: 'Gereja',
      B: 'Pura',
      C: 'Kelenteng',
      D: 'Mesjid',
    },
    answer: 'D',
  },
  {
    id: 92,
    text: 'Simbol tanda medan untuk danau berbentuk …',
    image: '',
    options: {
      A: 'Garis lurus',
      B: 'Gelombang',
      C: 'Area tertutup tidak beraturan',
      D: 'Segitiga',
    },
    answer: 'C',
  },
  {
    id: 93,
    text: 'Tanda jejak dengan tanda silang besar (X) berarti …',
    image: '',
    options: {
      A: 'Air bersih',
      B: 'Ikuti jalan ini',
      C: 'Jangan dilewati',
      D: 'Bahaya',
    },
    answer: 'D',
  },
  {
    id: 94,
    text: 'Tanda jejak berbentuk hati berarti …',
    image: '',
    options: {
      A: 'Bahaya',
      B: 'Air buruk',
      C: 'Keadaan buruk',
      D: 'Kembali',
    },
    answer: 'C',
  },
  {
    id: 95,
    text: 'Tanda jejak berbentuk lingkaran dengan panah berarti …',
    image: '',
    options: {
      A: 'Air bersih',
      B: 'Kembali',
      C: 'Bahaya',
      D: 'Perkemahan',
    },
    answer: 'B',
  },
  {
    id: 96,
    text: 'Pecahkan sandi pada gambar berikut.',
    image: '/images/questions/sandi-01.jpeg',
    options: {
      A: 'MANDALA SAPARUA',
      B: 'MANAGALA SAPARUA',
      C: 'MANGGALA SAPARUA',
      D: 'MANAGALA SAPUTRA',
      E: 'MANDALA SAMUDRA',
    },
    answer: 'B',
  },
  {
    id: 97,
    text: 'Pecahkan sandi pada gambar berikut.',
    image: '/images/questions/sandi-02.jpeg',
    options: {
      A: 'BATAS MONAS RAKIT',
      B: 'BATAS MONAS RAKYAT',
      C: 'BATAK MONAS RAKIT',
      D: 'BATAS MANAS RAKIT',
      E: 'BATAS MONAS RAKSA',
    },
    answer: 'A',
  },
  {
    id: 98,
    text: 'Pecahkan sandi pada gambar berikut.',
    image: '/images/questions/sandi-03.jpeg',
    options: {
      A: 'HILANG SERIBU',
      B: 'HILANG SEFIBU',
      C: 'HILANG SEBUAH',
      D: 'HIDANG SEFIBU',
      E: 'HILANG SEFIRA',
    },
    answer: 'B',
  },
  {
    id: 99,
    text: 'Pecahkan sandi pada gambar berikut.',
    image: '/images/questions/sandi-04.jpeg',
    options: {
      A: 'SAHABAT SETIA',
      B: 'SAHABAT SEHATI',
      C: 'SAHABAT SEJATI',
      D: 'SAHABAT SEJARAH',
      E: 'SAHABAT SEJUTA',
    },
    answer: 'C',
  },
  {
    id: 100,
    text: 'Pecahkan sandi pada gambar berikut.',
    image: '/images/questions/sandi-05.jpeg',
    options: {
      A: 'MONARKI ABSOLUT',
      B: 'MONARKI ABSURD',
      C: 'MONARKI ABSOLUS',
      D: 'MONARSI ABSOLUT',
      E: 'MONARKI ABSOLUTE',
    },
    answer: 'A',
  },
];
